name: Chromatic

on:
  push:

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest

    env:
      CI: true
      STORE_PATH:
      TURBO_TEAM: 'lib-sandbox'
      TURBO_API: 'http://127.0.0.1:9080'
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js 🏠
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions

      - name: Setup pnpm 🧑‍💼
        uses: pnpm/action-setup@v6.0.5
        with:
          run_install: false

      - name: Get pnpm store directory 📁
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache 📦
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: TurboRepo local server 💪
        uses: felixmosh/turborepo-gh-artifacts@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_TOKEN }}

      - name: Run build 🏗️
        run: pnpm build --filter=storybook
        env:
          TURBO_API: ${{ env.TURBO_API }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ env.TURBO_TEAM }}

      - name: Publish to Chromatic 🚢
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: apps/storybook/dist
          zip: true
